server:
  projectName: 'faasAdmin[测试环境]'
  port: 8089
#################### spring相关配置 ####################

spring:
  #########################Spring Boot Admin 配置项#########################
  boot:
    admin:
      # Spring Boot Admin Client 客户端的相关配置
      client:
        url: http://127.0.0.1:${server.port}/${spring.boot.admin.context-path} # 设置 Spring Boot Admin Server 地址
        instance:
          prefer-ip: true # 注册实例时，优先使用 IP
      # Spring Boot Admin Server 服务端的相关配置
      context-path: /admin # 配置 Spring
  #########################Quartz 配置项，对应 QuartzProperties 配置类#########################
  quartz:
    auto-startup: true # 测试环境，需要开启 Job
    scheduler-name: schedulerName # Scheduler 名字。默认为 schedulerName
    job-store-type: jdbc # Job 存储器类型。默认为 memory 表示内存，可选 jdbc 使用数据库。
    wait-for-jobs-to-complete-on-shutdown: true # 应用关闭时，是否等待定时任务执行完成。默认为 false ，建议设置为 true
    properties: # 添加 Quartz Scheduler 附加属性，更多可以看 http://www.quartz-scheduler.org/documentation/2.4.0-SNAPSHOT/configuration.html 文档
      org:
        quartz:
          # Scheduler 相关配置
          scheduler:
            instanceName: schedulerName
            instanceId: AUTO # 自动生成 instance ID
          # JobStore 相关配置
          jobStore:
            # JobStore 实现类。可见博客：https://blog.csdn.net/weixin_42458219/article/details/122247162
            class: org.springframework.scheduling.quartz.LocalDataSourceJobStore
            isClustered: true # 是集群模式
            clusterCheckinInterval: 15000 # 集群检查频率，单位：毫秒。默认为 15000，即 15 秒
            misfireThreshold: 60000 # misfire 阀值，单位：毫秒。
          # 线程池相关配置
          threadPool:
            threadCount: 25 # 线程池大小。默认为 10 。
            threadPriority: 5 # 线程优先级
            class: org.quartz.simpl.SimpleThreadPool # 线程池类型
    jdbc: # 使用 JDBC 的 JobStore 的时候，JDBC 的配置
      initialize-schema: NEVER # 是否自动使用 SQL 初始化 Quartz 表结构。这里设置成 never ，我们手动创建表结构。
  #########################数据源配置项#########################
  autoconfigure:
    exclude:
      - com.alibaba.druid.spring.boot.autoconfigure.DruidDataSourceAutoConfigure # 排除 Druid 的自动配置，使用 dynamic-datasource-spring-boot-starter 配置多数据源
  #########################数据库相关配置#########################
  datasource:
    druid: # Druid 【监控】相关的全局配置
      web-stat-filter:
        enabled: true
      stat-view-servlet:
        enabled: true
        allow: # 设置白名单，不填则允许所有访问
        url-pattern: /druid/*
        login-username: # 控制台管理用户名和密码
        login-password:
      filter:
        stat:
          enabled: true
          log-slow-sql: true # 慢 SQL 记录
          slow-sql-millis: 100
          merge-sql: true
        wall:
          config:
            multi-statement-allow: true
    dynamic: # 多数据源配置
      druid: # Druid 【连接池】相关的全局配置
        initial-size: 5 # 初始连接数
        min-idle: 10 # 最小连接池数量
        max-active: 20 # 最大连接池数量
        max-wait: 600000 # 配置获取连接等待超时的时间，单位：毫秒
        time-between-eviction-runs-millis: 60000 # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位：毫秒
        min-evictable-idle-time-millis: 300000 # 配置一个连接在池中最小生存的时间，单位：毫秒
        max-evictable-idle-time-millis: 900000 # 配置一个连接在池中最大生存的时间，单位：毫秒
        validation-query: SELECT 1 FROM DUAL # 配置检测连接是否有效
        test-while-idle: true
        test-on-borrow: false
        test-on-return: false
      primary: master
      datasource:
        master:
          name: faas-admin-db
          port: 3306
          url: jdbc:mysql://39.105.97.89:${spring.datasource.dynamic.datasource.master.port}/${spring.datasource.dynamic.datasource.master.name}?allowMultiQueries=true&useUnicode=true&useSSL=false&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&autoReconnect=true&nullCatalogMeansCurrent=true # MySQL Connector/J 8.X 连接的示例
          #driver-class-name: com.mysql.jdbc.Driver
          username: root
          password: root
        slave: # 模拟从库，可根据自己需要修改
          name: faas-admin-db
          port: 3306
          url: jdbc:mysql://39.105.97.89:${spring.datasource.dynamic.datasource.slave.port}/${spring.datasource.dynamic.datasource.slave.name}?allowMultiQueries=true&useUnicode=true&useSSL=false&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&autoReconnect=true&nullCatalogMeansCurrent=true # MySQL Connector/J 8.X 连接的示例
          #driver-class-name: com.mysql.jdbc.Driver
          username: root
          password: root
  #########################Redis 配置。Redisson 默认的配置足够使用，一般不需要进行调优#########################
  redis:
    host: 127.0.0.1 # 地址
    port: 6379 # 端口
    database: 3 # 数据库索引
  main:
    allow-bean-definition-overriding: true

#################### 监控相关配置 ####################

# Actuator 监控端点的配置项
management:
  endpoints:
    web:
      base-path: /actuator # Actuator 提供的 API 接口的根目录。默认为 /actuator
      exposure:
        include: '*' # 需要开放的端点。默认值只打开 health 和 info 两个端点。通过设置 * ，可以开放所有端点。

# 日志文件配置
logging:
  file:
    name: ${user.home}/logs/${spring.application.name}.log # 日志文件名，全路径

#################### 配置中心相关配置 ####################

# Apollo 配置中心
apollo:
  bootstrap:
    enabled: true # 设置 Apollo 在启动阶段生效
    eagerLoad:
      enabled: true # 设置 Apollo 在日志初始化前生效，可以实现日志的动态级别配置
  jdbc: # 自定义的 JDBC 配置项，用于数据库的地址
    dao: com.faasadmin.faas.business.infra.dal.mysql.config.InfraConfigDAOImpl
    url: ${spring.datasource.dynamic.datasource.master.url}
    username: ${spring.datasource.dynamic.datasource.master.username}
    password: ${spring.datasource.dynamic.datasource.master.password}

#################### 服务保障相关配置 ####################

# Lock4j 配置项
lock4j:
  acquire-timeout: 3000 # 获取分布式锁超时时间，默认为 3000 毫秒
  expire: 30000 # 分布式锁的超时时间，默认为 30 毫秒

# Resilience4j 配置项
resilience4j:
  ratelimiter:
    instances:
      backendA:
        limit-for-period: 1 # 每个周期内，允许的请求数。默认为 50
        limit-refresh-period: 60s # 每个周期的时长，单位：微秒。默认为 500
        timeout-duration: 1s # 被限流时，阻塞等待的时长，单位：微秒。默认为 5s
        register-health-indicator: true # 是否注册到健康监测

#################### faasadmin相关配置 ####################

# 配置项，设置当前项目所有自定义的配置
faasadmin:
  captcha:
    enable: false # 本地环境，暂时关闭图片验证码，方便登录等接口的测试
  swagger:
    # 是否开启swagger
    enabled: true
    # 请求前缀
    pathMapping: /dev-api
    title: 管理后台
    description: 提供管理员管理的所有功能
    version: ${faasadmin.version}
    base-package: ${faasadmin.base-package}.modules
  system:
    # 超级管理员ID
    superAdminId: 1
    # 超级管理员租户ID
    superAdminLesseeId: 1
  security:
    token-header: Authorization
    mock-enable: true
    mock-secret: test
  file:
    base-path: http://39.105.97.89:${server.port}${faasadmin.web.api-prefix}/system/db/file/download/
  xss:
    enable: false
    exclude-urls: # 如下两个 url，仅仅是为了演示，去掉配置也没关系
      - ${spring.boot.admin.context-path}/** # 不处理 Spring Boot Admin 的请求
      - ${management.endpoints.web.base-path}/** # 不处理 Actuator 的请求
  pay:
    pay-notify-url: http://niubi.natapp1.cc/api/pay/order/notify
    refund-notify-url: http://niubi.natapp1.cc/api/pay/refund/notify
  demo: false # 关闭演示模式
  # 插件的配置
  plugin:
    # 插件运行模式. dev: 开发环境, prod: 生产环境
    runMode: dev
    # 是否启用插件
    enable: true
    # 插件存放的目录
    #pluginPath: D:\idea_work\2022-03-8\faas-addons\addons-modules
    #pluginPath: D:\idea_work\2022-03-8\faas-addons\addons-modules
    #pluginPath: D:\idea_work\2022-03-8\empty
    #pluginPath: D:\data\2021\plugins\
    pluginPath: plugins
    # 生产环境下, 插件文件的路径. 只在生产环境下生效
    # pluginConfigFilePath: D:\data\2021\plugins\config
    # 插件rest接口前缀
    pluginRestPathPrefix: /plugins/
    # 在卸载插件后, 备份插件的目录
    backupPluginPath: backupPlugin
    # 上传的插件所存储的临时目录
    #uploadTempPath: D:\data\2020\
    uploadTempPath: uploadTemp
    # 禁用的插件id, 禁用后系统不会启动该插件. 为Set集合. 配置案例如下:
    disablePluginIds:
       - faas-diy-addons
       - faas-api-addons
       - decoration-addons
    #后端界面配置
    webLocation: classpath:/faasadmin-ui/
    # web 界面的配置
    config:
      # 服务的接口url地址, 默认为空, 表示使用浏览器访问的地址
      serverUrl: /
      # 前端插件请求插件接口的api前缀
      pluginApiPrefix: ${faasadmin.plugin.pluginRestPathPrefix}


# 社会化登陆
justauth:
  enabled: true
  type:
    GITEE: # Gitee
      client-id: ee61f0374a4c6c404a8717094caa7a410d76950e45ff60348015830c519ba5c1
      client-secret: 7c044a5671be3b051414db0cf2cec6ad702dd298d2416ba24ceaf608e6fa26f9
      ignore-check-redirect-uri: true
    DINGTALK: # 钉钉
      client-id: dingvrnreaje3yqvzhxg
      client-secret: i8E6iZyDvZj51JIb0tYsYfVQYOks9Cq1lgryEjFRqC79P3iJcrxEwT6Qk2QvLrLI
      ignore-check-redirect-uri: true
    WECHAT_ENTERPRISE: # 企业微信
      client-id: wwd411c69a39ad2e54
      client-secret: 1wTb7hYxnpT2TUbIeHGXGo7T0odav1ic10mLdyyATOw
      agent-id: 1000004
      ignore-check-redirect-uri: true
  cache:
    type: REDIS
    prefix: 'social_auth_state:' # 缓存前缀，目前只对 Redis 缓存生效，默认 JUSTAUTH::STATE::
    timeout: 24h # 超时时长，目前只对 Redis 缓存生效，默认 3 分钟